{% set name = "constructive_geometries" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/constructive_geometries-{{ version }}.tar.gz
  sha256: ac99977d2d27055cf698272c424e2a237b5d1ee038eef388f7c808ea43d944d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools >=68.0
    - python >=3.10
  run:
    - certifi
    - country_converter
    - fiona
    - python >=3.10
    - shapely
    - wrapt

test:
  imports:
    - constructive_geometries
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecoinvent/constructive_geometries/
  summary: Simple tools to define world locations from a set of topological faces and set algebra
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cmutel
    - xylar
