{% set python_min = '3.10' %}
{% set name = "constructive_geometries" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/constructive_geometries-{{ version }}.tar.gz
  sha256: 353fe0701a6dbb40a163d9d3b92572a6dc360437980db5cf25cfccfb987e7782

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=68.0
  run:
    - python >={{ python_min }}
    - country_converter
    - wrapt
    # gis extra
    - fiona
    - shapely

test:
  imports:
    - constructive_geometries
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ecoinvent/constructive_geometries/
  summary: Simple tools to define world locations from a set of topological faces and set algebra
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmutel
    - xylar
