{% set name = "constructive_geometries" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/constructive_geometries-{{ version }}.tar.gz
  sha256: 645ad2a20e28bbf84af4a7fee8264a5d7ead576570a702ebc285cb195d8dbadc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=68.0
    - pip
  run:
    - python >=3.10
    - country_converter
    - wrapt

test:
  imports:
    - constructive_geometries
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Simple tools to define world locations from a set of topological faces and set algebra
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cmutel
    - xylar
